name: "ECSStack-Plan"
on:
  workflow_dispatch:
  
jobs:
  plan-ecs-stack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_USER_KEY}}
          aws-secret-access-key: ${{secrets.AWS_USER_SECRET_KEY}}
          aws-region: "us-east-1"

      - name: Configure AWS profile
        uses: Fooji/create-aws-profile-action@v1
        with:
          profile: default
          region: us-east-1
          key:  ${{secrets.AWS_USER_KEY}}
          secret:  ${{secrets.AWS_USER_SECRET_KEY}}

      - name: Terraform Init
        id: init
        working-directory: ./dev-ops/terraform/
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        working-directory: ./dev-ops/terraform/
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./dev-ops/terraform/
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1